FROM node:10.8.0-jessie

ADD . /opt/app/
WORKDIR /opt/app

EXPOSE 8080

ENV NODE_ENV production

ENTRYPOINT node --perf-basic-prof-only-functions --interpreted-frames-native-stack --no-turbo-inlining src/index.js
